### ISSUE TITLE
Feature request , position, speed, time/date

### ISSUE THREAD

**Issue by trancen** [dride/dride-app-issues#10]
I know you have likely seen hundreds of videos and their HUD... Just thought I would share this layout for possible firmware update

[https://imgur.com/XvhouGt](url)

**Comment by saoron** [comment]
Will be released in the next FW version

**Comment by saoron** [comment]
Added in FW 2.0

https://github.com/dride/dride-app-issues/releases/tag/2.0-beta-1

Will be publicly released later this month,
Thanks for reporting about this.

**Comment by MyDefender** [comment]
I’m trying to update the firmware to the latest version on Github (2.0-beta-1) https://github.com/dride/dride-app-issues/releases/tag/2.0-beta-1. After updating and deleting the 'bin' file, the light stays red/white rather than pure white though and the firmware version says ‘DrideZero_V0.0.1’. Is that the correct or should the firmware version number be different? And why does the light not go pure white?
